version: '3.1'

services:
  web:
    build: ./
    depends_on:
      - db
    ports:
      - 127.0.0.1:19001:3000
  db:
    image: mongo:4.2
    restart: always
    ports:
      - 127.0.0.1:27017:27017
